-- ============================================================
-- FIX ODONTOLOGOS: RLS POLICIES & SEED DATA
-- JVCreative · Pro-Security Protocol
-- ============================================================

-- 1. Asegurar esquema de la tabla
CREATE TABLE IF NOT EXISTS public."ODONTOLOGOS" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "ODONTOLOGO" text NOT NULL,
    "ESPECIALIDAD" text DEFAULT 'Odontólogo General',
    "created_at" timestamptz DEFAULT now()
);

-- 2. Habilitar RLS si no lo está
ALTER TABLE public."ODONTOLOGOS" ENABLE ROW LEVEL SECURITY;

-- 3. POLÍTICAS DE ACCESO
-- A. LECTURA (Requerido para el Selector de Perfiles 'Login')
DROP POLICY IF EXISTS "Permitir lectura para todos" ON public."ODONTOLOGOS";
CREATE POLICY "Permitir lectura para todos"
ON public."ODONTOLOGOS"
FOR SELECT
TO anon, authenticated
USING (true);

-- B. INSERCIÓN/ACTUALIZACIÓN/BORRADO (Solo Admin - Simplificado por ahora)
DROP POLICY IF EXISTS "Solo Admin puede mutar" ON public."ODONTOLOGOS";
CREATE POLICY "Solo Admin puede mutar"
ON public."ODONTOLOGOS"
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. SEMILLAS (Si está vacía)
-- NOTA: DRA. LUCIA QUINTERO y ADMINISTRADORSACH son claves para el sistema
INSERT INTO public."ODONTOLOGOS" ("ODONTOLOGO", "ESPECIALIDAD")
SELECT 'DRA. LUCIA QUINTERO', 'Especialista en Ortodoncia'
WHERE NOT EXISTS (SELECT 1 FROM public."ODONTOLOGOS" WHERE "ODONTOLOGO" = 'DRA. LUCIA QUINTERO');

INSERT INTO public."ODONTOLOGOS" ("ODONTOLOGO", "ESPECIALIDAD")
SELECT 'ADMINISTRADORSACH', 'Super-Admin'
WHERE NOT EXISTS (SELECT 1 FROM public."ODONTOLOGOS" WHERE "ODONTOLOGO" = 'ADMINISTRADORSACH');

-- VERIFICACIÓN FINAL
SELECT * FROM public."ODONTOLOGOS";
