-- ESTRUCTURA DE TABLAS S.A.C.H. - JVCreative ---

-- 1. PACIENTES: Directorio principal de expedientes clínicos
CREATE TABLE IF NOT EXISTS public."PACIENTES" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "ID DEL PACIENTE" text UNIQUE NOT NULL, -- Cédula
    "NOMBRE DEL PACIENTE" text NOT NULL,
    "CELULAR DEL PACIENTE" text,
    "CORREO" text,
    "DIRECCION" text,
    "FECHA DE NACIMIENTO" text, -- Formato DD/MM/YYYY
    "SEXO" text,
    "EDAD" bigint,
    "OBSERVACIONES" text DEFAULT 'Sin observaciones',
    
    -- Sección B: Representante
    "NOMBRE REPRESENTANTE" text,
    "CEDULA REPRESENTANTE" text,
    "CELULAR DEL REPRESENTANTE" text,
    "CORREO REPRESENTANTE" text,

    -- Sección C: Facturador
    "NOMBRE FACTURACION" text,
    "CEDULA FACTURACION" text,
    "CELULAR FACTURACION" text,
    "CORREO FACTURACION" text,

    -- Anamnesis
    "RESPUESTA 01" text DEFAULT 'No',
    "RESPUESTA 02" text DEFAULT 'No',
    "RESPUESTA 03" text DEFAULT 'No',
    "RESPUESTA 04" text DEFAULT 'No',
    "RESPUESTA 05" text DEFAULT 'Normal',

    -- Data clínica (JSON)
    "odontograma_json" jsonb DEFAULT '[]'::jsonb,
    "presupuesto_json" jsonb DEFAULT '[]'::jsonb,
    "evolucion_clinica_json" jsonb DEFAULT '[]'::jsonb,
    "imagenes_json" jsonb DEFAULT '[]'::jsonb,
    
    "created_at" timestamptz DEFAULT now()
);

-- 2. CITAS: Agenda para gestión de turnos
CREATE TABLE IF NOT EXISTS public."CITAS" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "FECHA DE CITA" text NOT NULL, -- YYYY-MM-DD
    "HORA DE CITA" text NOT NULL, -- HH:MM
    "NOMBRE DEL PACIENTE" text NOT NULL,
    "MOTIVO DE CONSULTA" text,
    "TRATAMIENTO" text,
    "VALOR" float8 DEFAULT 0,
    "ABONO" float8 DEFAULT 0,
    "ID DEL PACIENTE" text, -- Cédula (Relación lógica)
    "NUMERO SILLON" text DEFAULT '1',
    "ESTADO" text DEFAULT 'Pendiente',
    "created_at" timestamptz DEFAULT now()
);

-- 3. ABONO: Registro detallado de ingresos financieros
CREATE TABLE IF NOT EXISTS public."ABONO" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "FECHA" text NOT NULL, -- YYYY-MM-DD
    "PACIENTE" text NOT NULL,
    "ABONO" float8 NOT NULL,
    "METODO PAGO" text DEFAULT 'Efectivo',
    "OBSERVACION" text,
    "ID PACIENTE" text, -- Cédula
    "created_at" timestamptz DEFAULT now()
);

-- 4. TRATAMIENTOS: El tarifario del sistema
CREATE TABLE IF NOT EXISTS public."TRATAMIENTOS" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "TRATAMIENTO" text NOT NULL,
    "VALOR" float8 NOT NULL DEFAULT 0,
    "CATEGORIA" text DEFAULT 'General',
    "created_at" timestamptz DEFAULT now()
);

--- FINAL DEL ESQUEMA ---
